### ISSUE TITLE
Renaming doesnt work with mounted Xeric's talisman

### ISSUE THREAD

**Issue by SandroVA** [LlemonDuck/easy-teleports#2]
As the title says both of these situations currently do not work.

**Comment by LlemonDuck** [comment]
Book of the Dead is an equipment panel only replacement by design, I felt the dialogue options were descriptive enough.

I'll look into the mounted Xeric's talisman.

If you would like the Book of the dead replacement in the dialogue options as well, feel free to open another issue as a feature request so I can separate the progress of the bug and the feature request.

**Comment by ashtongraves** [comment]
Also doesn't work with Ring of Dueling in the Jewelry  Box

**Comment by Nick2bad4u** [comment]
Having same issue as above. Would be nice to fix!

**Comment by Nick2bad4u** [comment]
> If you would like the Book of the dead replacement in the dialogue options as well, feel free to open another issue as a feature request so I can separate the progress of the bug and the feature request.

Would also +1 to this

**Comment by LlemonDuck** [comment]
Support added in 695069e27dddd4f98acb09d275595dbd64b91e91

**Comment by LlemonDuck** [comment]
> Also doesn't work with Ring of Dueling in the Jewelry Box

Split out to #13

**Comment by LlemonDuck** [comment]
> If you would like the Book of the dead replacement in the dialogue options as well, feel free to open another issue as a feature request so I can separate the progress of the bug and the feature request.

Split out to #14
